# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginPage (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Auth'

  # Pods for LoginPage (iOS)

end

target 'LoginPage (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginPage (macOS)

end
